cache:
 directories:
  - node_modules

deploy:
 github_token: $DEPLOY_GITHUB_TOKEN
 local_dir: build
 provider: pages
 skip_cleanup: true

env:
 - POSTCSS_THROW_ERROR=1

language: node_js

node_js:
 - node

sudo: false

install:
 - npm install

script:
 - webpack -p
